export const PIPE_TAGS  = {
    START : "START",
    INTEGRATION : "INTEGRATION",
    BUILDER : "BUILDER",
    DEPLOYER : "DEPLOYER",
    CHECKER : "CHECKER",
    ERROR_NOTIFIER : "ERROR_NOTIFIER",
    REPORT_NOTIFIER : "REPORT_NOTIFIER",
    ANY : "ANY"
}
